language: csharp
solution: HL7-dotnetcore.sln
mono: none
dotnet: 2.0.0
dist: trusty

branches:  
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

install:
# nuget install xunit.runner.console -version 2.3.1
  - dotnet restore src
  - dotnet restore test

script:
  - dotnet test test
