language: csharp
solution: HL7-dotnetcore.sln
mono: none
dotnet: 2.0.0
dist: trusty

branches:  
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number

install:
  - mono .nuget/nuget.exe restore <solution.sln> -Verbosity detailed
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.2.1 -OutputDirectory ./src/packages
# nuget install xunit.runner.console -version 2.3.1
  - dotnet restore src
  - dotnet restore test

script:
  - dotnet test test
