trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Managed
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Compile source
      inputs:
        command: 'build'
        projects: 'src/*.csproj'
        arguments: '--configuration Release'
        feedsToUse: 'select'
        versioningScheme: 'off'
    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: 'test'
        projects: 'test/*.csproj'
        testRunTitle: 'HL7-dotnetcore unit test'
        feedsToUse: 'select'
        versioningScheme: 'off'
- stage: Deploy
  jobs:
  - job: nuget
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Retrieving build artifacts
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: DotNetCoreCLI@2
      displayName: Prepare nuget package
      inputs:
        command: 'pack'
        feedsToUse: 'select'
        packagesToPack: '**/HL7-dotnetcore.csproj'
        versioningScheme: 'off'
    - task: NuGetCommand@2
      displayName: 'Publish nuget package'
      inputs:
        command: push
        packagesToPush: '**/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: Nuget.org
