# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Compile source
  inputs:
    command: 'build'
    projects: 'src/*.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: Unit tests
  inputs:
    command: 'test'
    projects: 'test/*.csproj'
    testRunTitle: 'HL7-dotnetcore unit test'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: 'src/*.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'